### ISSUE TITLE
Rights problem

### ISSUE THREAD

**Issue by valentinthirion** [abakus-it/sla#1]
There misses a file that gives access rights to users for models like "sla" (same for rules and action)
=> ACL

**Comment by valentinthirion** [comment]
It would be nicer to have a menu that allows the user to see all the SLA (+ rules + actions) available (for instance in the Sales config)

**Comment by valentinthirion** [comment]
It would be great to add a column in the contracts list to directly see the contracts that are SLA compliant

**Comment by bernarddelhez** [comment]
ACL created

**Comment by bernarddelhez** [comment]
SLA menu in Sales Configuration to see and edit SLA

**Comment by bernarddelhez** [comment]
Add SLA status
